### ISSUE TITLE
feat: tokens search

### ISSUE THREAD

**Issue by okjintao** [Badger-Finance/badger-ninja#6]
# Summary

- implement a token page search bar allowing users to filter tokens by name, symbol, or chain
- display a similar page to the provided figma when no tokens match

https://www.figma.com/file/6zYgzhJFnX0bNAk7ohEH4T/Badger-App?node-id=7632%3A302671

## Blocked 

https://github.com/Badger-Finance/badger-ninja/issues/7

**Comment by NamelsKing** [comment]
https://github.com/Badger-Finance/badger-ninja/pull/29
