### ISSUE TITLE
feat: upgrade tokens view

### ISSUE THREAD

**Issue by okjintao** [Badger-Finance/badger-ninja#7]
#  Summary

- update token page to correspond with the given mocks
- do not include the 'vaults' header piece

https://www.figma.com/file/6zYgzhJFnX0bNAk7ohEH4T/Badger-App?node-id=7599%3A351340

## Follow Up

https://github.com/Badger-Finance/badger-ninja/issues/6

**Comment by NamelsKing** [comment]
https://github.com/Badger-Finance/badger-ninja/pull/28
